import { generateOtp, hashOtp } from './otp';
interface Env { DB: D1Database; DOCUMENTS: R2Bucket; OTP_SECRET: string; MAIL_API_URL: string; MAIL_API_KEY: string; MAIL_FROM: string; DEV_MAIL?: string }
interface EmailProvider { sendLoginCode(email: string, code: string): Promise<void> }
class HttpEmailProvider implements EmailProvider { constructor(private env: Env) {} async sendLoginCode(email:string, code:string) { const response = await fetch(this.env.MAIL_API_URL,{method:'POST',headers:{authorization:`Bearer ${this.env.MAIL_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from:this.env.MAIL_FROM,to:email,template:'login-code',variables:{code}})}); if(!response.ok) throw new Error('Mail delivery failed'); } }
const json = (body: unknown, status=200) => Response.json(body,{status,headers:{'cache-control':'no-store'}});
async function userFromSession(request:Request, env:Env):Promise<string|null>{ const token=request.headers.get('authorization')?.replace(/^Bearer /,''); if(!token)return null; const row=await env.DB.prepare('SELECT user_id FROM sessions WHERE token_hash=? AND expires_at>?').bind(await hashOtp('session',token,env.OTP_SECRET),Date.now()).first<{user_id:string}>(); return row?.user_id??null; }
export default { async fetch(request:Request,env:Env):Promise<Response>{ const url=new URL(request.url); if(request.method==='POST'&&url.pathname==='/auth/request'){ const {email}=await request.json<{email:string}>(); if(!/^\S+@\S+\.\S+$/.test(email))return json({message:'If the address can receive mail, a code will arrive.'}); const recent=await env.DB.prepare('SELECT created_at FROM otp_codes WHERE email=? ORDER BY created_at DESC LIMIT 1').bind(email.toLowerCase()).first<{created_at:number}>(); if(recent&&Date.now()-recent.created_at<60_000)return json({message:'If the address can receive mail, a code will arrive.'}); const code=generateOtp(); await env.DB.prepare('UPDATE otp_codes SET used=1 WHERE email=?').bind(email.toLowerCase()).run(); await env.DB.prepare('INSERT INTO otp_codes(id,email,code_hash,expires_at,attempts,used,created_at) VALUES(?,?,?,?,0,0,?)').bind(crypto.randomUUID(),email.toLowerCase(),await hashOtp(email,code,env.OTP_SECRET),Date.now()+600_000,Date.now()).run(); await new HttpEmailProvider(env).sendLoginCode(email,code); return json({message:'If the address can receive mail, a code will arrive.'}); }
if(request.method==='PUT'&&url.pathname.startsWith('/objects/')){const user=await userFromSession(request,env);if(!user)return json({error:'Unauthorized'},401);const [, , documentId, kind]=url.pathname.split('/');if(!/^[a-f0-9-]{16,64}$/.test(documentId)||!['original','page'].includes(kind))return json({error:'Invalid object'},400);await env.DOCUMENTS.put(`users/${user}/documents/${documentId}/${kind}`,request.body);return json({ok:true});}
if(request.method==='DELETE'&&url.pathname==='/account'){const user=await userFromSession(request,env);if(!user)return json({error:'Unauthorized'},401);await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(user).run();await env.DB.prepare('DELETE FROM entities WHERE user_id=?').bind(user).run();await env.DB.prepare('DELETE FROM users WHERE id=?').bind(user).run();for(const object of (await env.DOCUMENTS.list({prefix:`users/${user}/`})).objects)await env.DOCUMENTS.delete(object.key);return json({ok:true});} return json({error:'Not found'},404); } };
